# frozen_string_literal: true

require "test_helper"

# Engine invariant tests for the pure projection engine. These encode the
# cross-cutting guarantees from spec "Engine Invariants" that apply to the
# income/spending proof slice:
#
#   - Same packet + engine version is deterministic (byte-identical output).
#   - Disabled assumptions produce no flows but remain explainable.
#   - Income and spending affect cash + net worth with traceable categories.
#   - Missing FX, missing security price, and invalid milestone references
#     produce plan issues, NOT uncaught exceptions.
#
# Invariants for flow kinds this slice does not yet expand (transfers, debt,
# portfolio return, actualization, scenario layer mutation) are covered by their
# own slices' golden fixtures; this file asserts only what the current engine
# semantics guarantee.
class Forecasts::Projection::EngineInvariantsTest < ActiveSupport::TestCase
  HORIZON_START = "2026-01-01"
  HORIZON_END = "2029-01-01" # 36 months

  def salary_assumption(overrides = {})
    {
      id: "assumption-salary-1",
      kind: "salary",
      status: "active",
      scenario_layer_id: nil,
      params: {
        person_key: "primary",
        amount: "6000.00",
        gross_or_net: "net",
        currency: "USD",
        frequency: "monthly",
        growth_policy: { type: "none" },
        start_anchor: { type: "date", on: HORIZON_START },
        end_anchor: nil
      }
    }.merge(overrides)
  end

  def living_expense_assumption(overrides = {})
    {
      id: "assumption-expense-1",
      kind: "living_expense",
      status: "active",
      scenario_layer_id: nil,
      params: {
        amount: "4000.00",
        currency: "USD",
        frequency: "monthly",
        category_ids: %w[cat-groceries cat-rent],
        inflation_policy: { type: "none" },
        actualization_policy: { type: "none" },
        start_anchor: { type: "date", on: HORIZON_START },
        end_anchor: nil
      }
    }.merge(overrides)
  end

  def packet_attributes(assumptions: nil, source_overrides: {}, milestones: [])
    {
      schema_version: 1,
      engine_version: "forecast_v2.1",
      plan: {
        id: "plan-1",
        family_id: "family-1",
        version: 7,
        reporting_currency: "USD",
        horizon: {
          starts_on: HORIZON_START,
          ends_on: HORIZON_END,
          near_term_daily_days: 90
        }
      },
      scenario_stack: { key: "baseline", layer_ids: [] },
      milestones: milestones,
      assumptions: assumptions || [ salary_assumption, living_expense_assumption ],
      scenario_operations: [],
      source_snapshot: {
        as_of: "2026-01-01T00:00:00Z",
        reporting_currency: "USD",
        opening_balances: { liquid_cash: "10000.00", debt_balance: "0.00", portfolio_value: "0.00" },
        accounts: [],
        transactions: [],
        recurring_patterns: [],
        debts: [],
        holdings: [],
        prices: [],
        fx_rates: []
      }.merge(source_overrides),
      issue_policy: { missing_fx: "issue_limited", missing_price: "issue_limited", invalid_assumption: "block_recompute" }
    }
  end

  def build_packet(**kwargs)
    Forecasts::Projection::Packet.new(packet_attributes(**kwargs))
  end

  def call(**kwargs)
    Forecasts::Projection::Engine.call(build_packet(**kwargs))
  end

  # --- Determinism ---------------------------------------------------------

  test "the same packet and engine version produce byte-identical output" do
    packet = build_packet

    first = Forecasts::Projection::Engine.call(packet).to_h
    second = Forecasts::Projection::Engine.call(packet).to_h

    assert_equal first, second
    # A separately constructed but identical packet must also match, proving the
    # result depends only on packet content (not object identity or call order).
    third = Forecasts::Projection::Engine.call(build_packet).to_h
    assert_equal first, third
  end

  test "determinism extends to the input packet hash" do
    assert_equal build_packet.input_packet_hash, build_packet.input_packet_hash
  end

  # --- Disabled assumptions remain explainable -----------------------------

  test "disabled assumptions produce no flows but remain in the packet" do
    disabled_salary = salary_assumption(status: "disabled")
    packet = build_packet(assumptions: [ disabled_salary, living_expense_assumption ])
    result = Forecasts::Projection::Engine.call(packet)

    # No income flow/trace is generated by the disabled assumption.
    income_traces = result.traces.select { |trace| trace.assumption_id == "assumption-salary-1" }
    assert_empty income_traces
    refute_includes result.traces.map(&:category), "income"

    # ...but it is still present in the packet, so the editor can explain it.
    disabled = packet.assumptions.find { |a| a[:id] == "assumption-salary-1" }
    refute_nil disabled, "disabled assumption must remain in the packet for the editor"
    assert_equal "disabled", disabled[:status]
  end

  test "an archived assumption likewise produces no flows" do
    result = call(assumptions: [ salary_assumption(status: "archived"), living_expense_assumption ])

    refute_includes result.traces.map(&:category), "income"
  end

  # --- Income + spending affect cash and net worth, traceably --------------

  test "income and spending move liquid cash and net worth" do
    result = call
    jan = result.periods.first

    # 10_000 opening + 6_000 income - 4_000 spending = 12_000.
    assert_equal "12000.00", jan[:metrics][:liquid_cash]
    assert_equal "12000.00", jan[:metrics][:net_worth]
    assert_equal "6000.00", jan[:metrics][:income]
    assert_equal "4000.00", jan[:metrics][:spending]
  end

  test "every income and spending effect is traceable to a category and assumption" do
    result = call

    income = result.traces.select { |trace| trace.category == "income" }
    spending = result.traces.select { |trace| trace.category == "spending" }

    refute_empty income
    refute_empty spending
    assert income.all? { |trace| trace.assumption_id == "assumption-salary-1" }
    assert spending.all? { |trace| trace.assumption_id == "assumption-expense-1" }
    # Each period that has a metric movement references the traces causing it.
    jan = result.periods.first
    jan_trace_ids = result.traces.select { |t| t.period_key == "2026-01" }.map(&:id).sort
    assert_equal jan_trace_ids, jan[:trace_ids].sort
  end

  test "removing income lowers net worth growth, preserving the cash invariant" do
    with_income = call.periods.last[:metrics][:net_worth]
    without_income = call(assumptions: [ living_expense_assumption ]).periods.last[:metrics][:net_worth]

    assert_operator BigDecimal(with_income), :>, BigDecimal(without_income)
  end

  # --- Missing FX -> plan issue, not exception -----------------------------

  test "a missing FX rate produces a plan issue instead of raising" do
    foreign_salary = salary_assumption(
      id: "assumption-salary-eur",
      params: salary_assumption[:params].merge(currency: "EUR")
    )

    result = assert_nothing_raised do
      call(assumptions: [ foreign_salary, living_expense_assumption ])
    end

    assert_equal "issue_limited", result.status
    assert_includes result.issues.map(&:code), "missing_fx_rate"
    # The issue is structured (severity + remediation actions), not raw text.
    fx_issue = result.issues.find { |issue| issue.code == "missing_fx_rate" }
    assert_equal "error", fx_issue.severity
    refute_empty fx_issue.actions
  end

  # --- Missing security price -> no exception ------------------------------

  test "holdings without a price do not raise an exception" do
    # The proof-slice engine simulates cash income/spending only and does not
    # expand portfolio holdings yet, so a priceless holding must not crash the
    # engine. The full missing_security_price issue lands with the portfolio
    # slice; the invariant asserted here is "plan issue, not exception" — the
    # engine returns a usable result rather than blowing up.
    snapshot = {
      holdings: [ { id: "holding-1", security_id: "sec-1", quantity: "10" } ],
      prices: []
    }

    result = assert_nothing_raised do
      call(source_overrides: snapshot)
    end

    assert_includes Forecasts::Projection::Result::STATUSES, result.status
    refute_nil result.periods.first
  end

  # --- Invalid milestone reference -> blocking plan issue, not exception ----

  test "an unresolved milestone reference produces a blocking plan issue" do
    milestone_salary = salary_assumption(
      params: salary_assumption[:params].merge(
        start_anchor: { type: "milestone", milestone_key: "does-not-exist" }
      )
    )

    result = assert_nothing_raised do
      call(assumptions: [ milestone_salary, living_expense_assumption ])
    end

    assert_equal "blocked", result.status
    issue = result.issues.find { |i| i.code == "invalid_milestone_reference" }
    refute_nil issue, "expected an invalid_milestone_reference plan issue"
    assert_equal "blocking", issue.severity
    assert_equal "plan_validation", issue.source
    assert_equal "assumption-salary-1", issue.affected_entity_id
    # The affected assumption simply contributes no flows; other assumptions
    # still simulate, so the projection stays usable.
    refute_includes result.traces.map(&:category), "income"
    assert_includes result.traces.map(&:category), "spending"
  end

  test "a resolved milestone reference expands normally without an issue" do
    milestone_salary = salary_assumption(
      params: salary_assumption[:params].merge(
        start_anchor: { type: "milestone", milestone_key: "job-start" }
      )
    )

    result = call(
      assumptions: [ milestone_salary, living_expense_assumption ],
      milestones: [ { key: "job-start", resolved_on: HORIZON_START } ]
    )

    assert_equal "clean", result.status
    assert_empty result.issues
    assert_includes result.traces.map(&:category), "income"
  end

  test "an unknown anchor type produces a blocking plan issue, not an exception" do
    bad_salary = salary_assumption(
      params: salary_assumption[:params].merge(start_anchor: { type: "bogus" })
    )

    result = assert_nothing_raised do
      call(assumptions: [ bad_salary, living_expense_assumption ])
    end

    assert_equal "blocked", result.status
    assert_includes result.issues.map(&:code), "invalid_assumption_params"
  end
end
